version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_package:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn build
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-nextjs-app .
      - run:
          name: Save Docker Image
          command: |
            docker save -o nextjs-app.tar your-nextjs-app

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_package
